package com.lealpy.help_app.presentation.utils

object Const {

    const val LOG_TAG = "HelpAppLog"

    const val AUTHORIZATION_FEATURE_EMAIL_KEY = "AUTHORIZATION_FEATURE_EMAIL_KEY"
    const val AUTHORIZATION_FEATURE_PASSWORD_KEY = "AUTHORIZATION_FEATURE_PASSWORD_KEY"

    const val SEARCH_FEATURE_POSITION_SEARCH_BY_EVENTS = 0
    const val SEARCH_FEATURE_POSITION_SEARCH_BY_NKO = 1

    const val PROFILE_FEATURE_DIALOG_RESULT_KEY = "PROFILE_FEATURE_DIALOG_RESULT_KEY"
    const val PROFILE_FEATURE_CHOOSE_PHOTO_KEY = "PROFILE_FEATURE_CHOOSE_PHOTO_KEY"
    const val PROFILE_FEATURE_TAKE_PHOTO_KEY = "PROFILE_FEATURE_TAKE_PHOTO_KEY"
    const val PROFILE_FEATURE_DELETE_PHOTO_KEY = "PROFILE_FEATURE_DELETE_PHOTO_KEY"

    const val NEWS_FEATURE_NEWS_ID_KEY = "NEWS_FEATURE_NEWS_ID_KEY"
    const val NEWS_FEATURE_NEWS_TITLE_KEY = "NEWS_FEATURE_NEWS_TITLE_KEY"

    const val DONATE_MONEY_FEATURE_DONATION_AMOUNT_KEY = "DONATE_MONEY_FEATURE_DONATION_AMOUNT_KEY"
    const val DONATE_MONEY_FEATURE_IS_FIRST_NOTIFICATION_KEY =
        "DONATE_MONEY_FEATURE_IS_FIRST_NOTIFICATION_KEY"
    const val DONATE_MONEY_FEATURE_ILLEGAL_NEWS_ID = -1L
    const val DONATE_MONEY_FEATURE_ILLEGAL_DONATION_AMOUNT = -1
    const val DONATE_MONEY_FEATURE_DONATION_OFFER_1_KEY =
        "DONATE_MONEY_FEATURE_DONATION_OFFER_1_KEY"
    const val DONATE_MONEY_FEATURE_DONATION_OFFER_2_KEY =
        "DONATE_MONEY_FEATURE_DONATION_OFFER_2_KEY"
    const val DONATE_MONEY_FEATURE_DONATION_OFFER_3_KEY =
        "DONATE_MONEY_FEATURE_DONATION_OFFER_3_KEY"
    const val DONATE_MONEY_FEATURE_DONATION_OFFER_4_KEY =
        "DONATE_MONEY_FEATURE_DONATION_OFFER_4_KEY"

}
